FROM openjdk:19-jdk
WORKDIR /app
COPY build/libs/authentication-service-0.0.1-SNAPSHOT.jar /app/authentication-service-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-jar", "authentication-service-0.0.1-SNAPSHOT.jar"]


